### ISSUE TITLE
custom BASE_PATH support

### ISSUE THREAD

**Issue by ugenk** [netdevopsbr/netbox-proxbox#108]
Hello.

For now your awesome project does not support installations of netbox with custom BASE_PATH setting.

I implemented that functionality, but for some reason i'm not able to fork the repo to push the changes.

Attaching the diff:

[proxbox_base_path_support.patch](https://github.com/netdevopsbr/netbox-proxbox/files/11450984/proxbox_base_path_support.patch)

**Comment by emersonfelipesp** [comment]
Hi @ugenk! I follow the [NetBox's Official Contributing Guide](https://github.com/netbox-community/netbox/blob/develop/CONTRIBUTING.md) in Proxbox, I would like to have you opening a PR, as you authored this new feature, aswell so that you appears as contributor to code, as deserved. Thank you!

**Comment by ugenk** [comment]
Yeah, did it.

**Comment by emersonfelipesp** [comment]
Merged! Thank you again.
