### ISSUE TITLE
Multiple Proxmox Clusters

### ISSUE THREAD

**Issue by beerygaz** [netdevopsbr/netbox-proxbox#123]
How could the code be adapted to support multiple Proxmox clusters?  We run Dev, Test, 3xProd clusters.  Is this something trivial or would it require re-architecture of the plugin?

**Comment by emersonfelipesp** [comment]
Check recent release of **[Add multi-cluster support](https://github.com/netdevopsbr/netbox-proxbox/pull/122)** and let me know if it works on you environment!
