### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by jonaswestphal** [netdevopsbr/netbox-proxbox#144]
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed`

Disabling SSL on Proxmox is not possible.

```
Max retries exceeded with url: /api2/json/cluster/status (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

Python version: 3.10.12
NetBox version: 3.6.0
Plugins: 
  netbox_proxbox: 0.0.5
```

Can I disable SSL Certificate Validation in the configuration.py?

**Comment by chodorenko** [comment]
you can use `'ssl': False` in settings

**Comment by emersonfelipesp** [comment]
@jonaswestphal have you solved this issue with @chodorenko solution? SSL support is not fully developed yet.

**Comment by gurubert** [comment]
The base issue is that the Python virtualenv in which NetBox runs contains its own certifi module with its own CA certificates file. It does not use the system provided CA certificates.

**Comment by emersonfelipesp** [comment]
#32
