### ISSUE TITLE
migration error .. and SSL.. Of course.

### ISSUE THREAD

**Issue by dgarner-cg** [netdevopsbr/netbox-proxbox#170]
(venv) root@netbox:/opt/netbox/netbox# python3 manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_inventory, netbox_proxbox, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  No migrations to apply.
  Your models in app(s): 'netbox_proxbox' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

Further, I am running into the same error as everyone else when trying to use this on Proxmox with self signed certificate from Proxmox, which cannot be added to the trusted store for some stupid reason.

**Comment by dgarner-cg** [comment]
Also, this..

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'KeyError'>

'name'

Python version: 3.11.2
NetBox version: 3.6.5
Plugins: 
  netbox_inventory: 1.5.2
  netbox_proxbox: 0.0.5

**Comment by emersonfelipesp** [comment]
#32
