### ISSUE TITLE
Support Netbox v3.2.0

### ISSUE THREAD

**Issue by emersonfelipesp** [netdevopsbr/netbox-proxbox#36]

**Comment by ryanmerolle** [comment]
[NetBox 3.2.0](https://github.com/netbox-community/netbox/releases/tag/v3.2.0) was just released and has a number of [extension improvements](https://github.com/netbox-community/netbox/issues/8333).

Furthermore, a [NetBox 3.2 plugin tutorial](https://github.com/netbox-community/netbox-plugin-tutorial) was released
