### ISSUE TITLE
ImportError: cannot import name 'BaseTable'

### ISSUE THREAD

**Issue by ettorsson** [netdevopsbr/netbox-proxbox#42]
When I am running 
(venv) $ python3 manage.py migrate

I am getting this error message

  File "/opt/netbox-3.2.0/venv/lib64/python3.8/site-packages/netbox_proxbox/tables.py", line 3, in <module>
    from utilities.tables import BaseTable
ImportError: cannot import name 'BaseTable' from 'utilities.tables' (/opt/netbox-3.2.0/netbox/utilities/tables.py)

Netbox version 3.2.0
Proxbox version 0.0.2
Python 3.8.12

**Comment by pfr-l** [comment]
same problem :/

**Comment by emersonfelipesp** [comment]
This Issue was solved on PR https://github.com/netdevopsbr/netbox-proxbox/pull/44
