### ISSUE TITLE
footer.html error django.template.exceptions.TemplateDoesNotExist

### ISSUE THREAD

**Issue by quiknick** [netdevopsbr/netbox-proxbox#45]
<class 'django.template.exceptions.TemplateDoesNotExist'>

footer.html

Python version: 3.8.10
NetBox version: 3.2.0
Netbox-proxbox 0.0.4

If I comment out footer.html on the following files in netbox_proxbox/templates/netbox_proxbox/ everything works fine. 
proxmox_vm_full_update.html
proxmox_vm_list.html
home.html

**Comment by emersonfelipesp** [comment]
You must follow the following section of Installation Guide [available here](https://github.com/netdevopsbr/netbox-proxbox/blob/develop/README.md):

---

#### 1.3.2. Change Netbox '**[settings.py](https://github.com/netbox-community/netbox/blob/develop/netbox/netbox/settings.py)**' to include Proxbox Template directory

> Probably on the next release of Netbox, it will not be necessary to make the configuration below! As the [Pull Request #8733](https://github.com/netbox-community/netbox/pull/8734) got merged to develop branch

Edit **/opt/netbox/netbox/netbox** and find TEMPLATE_DIR section

- How it is configured (Netbox >= v3.2.0):
```python
TEMPLATES_DIR = BASE_DIR + '/templates'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'utilities.templatetags.builtins.filters',
                'utilities.templatetags.builtins.tags',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'netbox.context_processors.settings_and_registry',
            ],
        },
    },
]
```

<br>

- How it is must be:
```python
TEMPLATES_DIR = BASE_DIR + '/templates'

# PROXBOX CUSTOM TEMPLATE
PROXBOX_TEMPLATE_DIR = BASE_DIR + '/netbox-proxbox/netbox_proxbox/templates/netbox_proxbox'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR, PROXBOX_TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'utilities.templatetags.builtins.filters',
                'utilities.templatetags.builtins.tags',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'netbox.context_processors.settings_and_registry',
            ],
        },
    },
]
```
I did it because I had to change the **base/layout.html** from Netbox, since there is no **Jinja2 block** to fill with custom information into the **footer HTML tag**

**Comment by quiknick** [comment]
Muito obrigado! I was missing the 'DIRS': [TEMPLATES_DIR, PROXBOX_TEMPLATE_DIR],
