### ISSUE TITLE
problem : /plugins/proxbox/full_update/

### ISSUE THREAD

**Issue by Arcroww** [netdevopsbr/netbox-proxbox#63]
<class 'pynetbox.core.query.RequestError'>

The request failed with code 400 Bad Request but more specific details were not returned in json. Check the NetBox Logs or investigate this exception's error attribute.

Python version: 3.9.2
NetBox version: 3.2.5

**Comment by jonastra** [comment]
Getting same error.

Python version: 3.8.10
Netbox version: 3.3.1

**Comment by JouanDeag** [comment]
See #59
