### ISSUE TITLE
Problem open template 

### ISSUE THREAD

**Issue by NikolaTes2** [netdevopsbr/netbox-proxbox#64]
The complete exception is provided below:

<class 'django.template.exceptions.TemplateDoesNotExist'>

footer.html

Python version: 3.9.6
NetBox version: 3.2.2

version netbox-proxbox 0.04

**Comment by JouanDeag** [comment]
Look at step 1.3.2. in the README

**Comment by vrelk** [comment]
Unfortunately, I too am having this issue, even after making the changes, running the migration again, and restarting the service.

`Python version: 3.10.4`
`NetBox version: 3.2.5`
`netbox-proxbox 0.0.4`

**Comment by Thiritin** [comment]
I appear to have the same issue. I have made the changes in settings.py and restarted the server + service but had no success. still the error.

**Comment by slipdip123** [comment]
I'm getting the same error, I have made the changes as described by the README and I still get the server error.

**Comment by Thiritin** [comment]
I was able to install and run successfully by installing the developer version and removing all occurrences of footer.html manually. I am unsure why this is causing so much trouble.

**Comment by syswipe** [comment]
the same problem. any suggestions?
