### ISSUE TITLE
Multiple datacenter configuratrion

### ISSUE THREAD

**Issue by karnow98** [netdevopsbr/netbox-proxbox#65]
Hello,
I have many proxmox datacener. I would like proxbox to be configured to be able to retrieve data from each of them. Unfortunately, I can't configure it that way. In the 'settings.py' file I tried to duplicate the 'proxmox' or 'netbox_proxbox' sections, but the second settings overwritten the former.

Is it possible to configure a proxbox with multiple proxmox instances at all? 

Thank you in advance for your help

**Comment by urobasa** [comment]
very limited use in case of adding 1 cluster data center.
I have the same configuration and only one proxymox data center in this plugin does not allow it to be used in any serious cluster separation.

**Comment by daschaefer** [comment]
same here
