### ISSUE TITLE
Interfaces are updated event though it's not needed

### ISSUE THREAD

**Issue by MrBE4R** [netdevopsbr/netbox-proxbox#94]
Hi,

Due to some inconsistencies between the following lines :
https://github.com/netdevopsbr/netbox-proxbox/blob/v0.0.5/netbox_proxbox/proxbox_api/updates/virtual_machine.py#L310
https://github.com/netdevopsbr/netbox-proxbox/blob/v0.0.5/netbox_proxbox/proxbox_api/updates/virtual_machine.py#L327

The plugin detect that it should update the interfaces.

We should either force `.lower()` or `.upper()` on both to avoid false positive.

Cheers.

**Comment by emersonfelipesp** [comment]
Hi @MrBE4R could you please review if it is ok like the way I did?
I kept the regex considering lower case and if it matches, I use .upper() as I think it may be better readable.
Thank you already!

**Comment by MrBE4R** [comment]
Hi @emersonfelipesp that's what I did to correct our instance.

Cheers
